### ISSUE TITLE
R-snowleopard.jss recipe is now getting the 10.9.x and later version of R.

### ISSUE THREAD

**Issue by rtrouton** [autopkg/golbiga-recipes#2]
I noticed that AutoPkg downloaded a new R 3.3.1 installer for the 10.6.x - 10.8.x version of R. When I tested it, I saw that this was actually the R 3.3.1 installer for 10.9.x and later.

When I checked the `.download` recipe for R in `hjuutilainen-recipes`, it looks like the OS-specific check has been removed from the `.download` recipe:

[https://github.com/autopkg/hjuutilainen-recipes/commit/c3d5e772fa36dc9a842aa630dc6d484aab4abb7d](https://github.com/autopkg/hjuutilainen-recipes/commit/c3d5e772fa36dc9a842aa630dc6d484aab4abb7d)

**Comment by golbiga** [comment]
Since the .download recipe has changed, I'm going to retire this recipe.
