### ISSUE TITLE
Papers3 recipe does not work

### ISSUE THREAD

**Issue by grahampugh** [autopkg/golbiga-recipes#5]
When I download Papers3 using the Papers3.pkg recipe, and install the pkg, the app is damaged.  It only works if I then click on "Visit website", download the DMG, accept the Terms & Conditions, and drag-drop the app to /Applications.

**Comment by golbiga** [comment]
Sorry for the late response. I haven't supported Papers for a few years now. I would recommend using [Elliot's Papers recipe](https://github.com/autopkg/homebysix-recipes/tree/master/Papers). There was an issue with their App that Elliot solved. [See here](https://derflounder.wordpress.com/2016/06/06/diagnosing-and-fixing-code-signing-issues-for-applications-installed-by-installer-packages). I'll close this issue and remove the Papers 3 recipe.
